---
# Handlers for system_update role

- name: restart docker
  systemd:
    name: docker
    state: restarted
  become: true
  when: ansible_os_family != "Darwin"

- name: reboot system
  reboot:
    reboot_timeout: 600
    connect_timeout: 20
  become: true